logging:
  level:
    root: info
    com.blog: debug
  file:
    name: log/blog-dev.log
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&useUnicode=true&allowMultiQueries=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: ljcdh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true